version: '3'
services:

  database:
    image: "postgres:latest"
    ports:
      - "${PORT_DB}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - api-network
    restart: always

  redis:
    image: "redis:alpine"
    ports:
      - "${REDIS_PORT}:6379"
    command: [ "redis-server", "--bind", "redis", "--port", "${REDIS_PORT}" ]
    networks:
      - api-network
    restart: always

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "${REDIS_CLIENT_PORT}:8001"
    networks:
      - api-network
    restart: always

  api:
    build: .
    env_file:
      - .env
    ports:
      - "${APP_API_PORT}:${APP_API_PORT}"
    depends_on:
      - database
      - redis
    networks:
      - api-network
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn dev

networks:
  api-network:
    driver: bridge
